- targets:  # url;humanname;routing;switch
    - https://rcuspace.com/;rcuspace.com;external;internetbox
    - https://temmysdj.com/;temmysdj.com;external;internetbox
    - https://sofreshrecords.club/;sofreshrecords.club;external;internetbox
    - https://yisusvii.com/;yisusvii.com;external;internetbox

    # - http://192.168.1.1;internetbox;local;internetbox
    # - http://192.168.1.42;blackdata;local;orbirouter-attic
    # - http://192.168.1.101;orbirouter;local;orbirouter

